### ISSUE TITLE
[Feature request] Load websites for thumbnails generation into private mode

### ISSUE THREAD

**Issue by reverse123** [k-ivan/visual-bookmarks-chrome#134]
When generating previews for bookmarked youtube videos, they appears in my account watch history and browser history too.
It would be nice to not place them into browser history, and do not use browser session cookies when loading site.
You can watch how to open tabs with separate cookies sessions from this small extension:
https://chrome.google.com/webstore/detail/multilogin/ijfgglilaeakmoilplpcjcgjaoleopfi

**Comment by k-ivan** [comment]
To be honest, I don't see the point in it.  One of the reasons for generating screenshots was to get a screenshot of the actual page, and not a login form(for example social network website). So I think this behavior is correct.  

Generation leaves a record in the history is also logical, because we go to this site for generation.  in theory, it can be cleared, but there is a risk of clearing the data that we can open at the time of generation (for example, opening a site in parallel with generating screenshots).

**Comment by k-ivan** [comment]
Closing as I think both questions are correct behavior. 

It could be added with history, but for now I don’t want to add another permission to access the user’s history and I don’t see 
the need for this option.
