### ISSUE TITLE
Suggestions for working with several thumbnails at once

### ISSUE THREAD

**Issue by visbook** [k-ivan/visual-bookmarks-chrome#150]
With the introduction of the new Quick Actions Panel and using “shift+click” it is now possible to select several thumbnails at once and open, delete, refresh and move them, which is a great help for working with thumbnails, and means you no longer have to use the browsers “Bookmarks” folders to perform these operations to more than one thumbnail.

Two more features that would be very welcome (if at all possible) are if users could also do the following actions inside of VB folders-

1) In some folders I have 50-100 thumbnails and if I want to select for example thumbnails 40 to 60 to move or delete them, presently I have to “shift+click” each one individually which is quite time consuming.

- [x] It would be so much easier if I could select a “range” of thumbnails by just shift-clicking thumbnail 40 then shift-clicking thumbnail 60 and thumbnails 41-59 were automatically added to the selection.
Maybe another keyboard combination such as “Shift+Alt+Click” when selecting the first and last thumbnail could tell VB it’s selecting a range.

2) It is very easy to drag & drop single thumbnails around inside of VB and do things like re-arrange them in a folder or drag one into its parent folder, but you can only do this one thumbnail at a time.

- [ ] #152

Would any of these suggestions be feasible k-ivan?

**Comment by k-ivan** [comment]
Hello, interesting features.

1. I also thought about this possibility since adding the panel. I'll think about this first. It might be possible to implement it.

2. But multiple drag and drop cannot be added at the moment. Because I will need my own drag and drop implementation. Perhaps in the future I will try to implement my own drag-and-drop mechanism, then a few more problems will be solved, but this is not in the plans yet.

**Comment by visbook** [comment]
It's good that my ideas may be possible, and us grateful VB users know that whatever you decide to add, will be worth the wait.
