### ISSUE TITLE
Requesting a Firefox port

### ISSUE THREAD

**Issue by brokoler** [k-ivan/visual-bookmarks-chrome#36]
Hello k-ivan,

I discovered Visual Bookmarks for Chrome and was stunned by the quality of this extension. It's exactly what I was looking for, I searched for such an addon long time.

It would be really great if the extension would be ported to Firefox, which is in many ways a more privacy oriented browser. There is no addon that compares to Visual Bookmarks.

Do you have any plans to port the addon?

**Comment by k-ivan** [comment]
Hi eggplanting!

Good suggestion, I also thought about it. But there are difficulties. For example, the FileSystem API is used to generate thumbnails. I could be wrong, but at the moment Firefox does not support this API. Therefore, at the moment I do not see the possibility of a full port. 
And I do not have the ability to have an external cdn server to save thumbnails on it. In this case, the FileSystem API was a great solution (despite the fact that not everyone likes that it requires wide permissions).
I would also like to make an extension for Firefox and that would be a great experience. So I hope that it will be possible, but maybe a little later.

**Comment by notiv-nt** [comment]
@k-ivan what about [this article?](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API/Firefox_support) Can the extension be ported now?
You are considering other possibilities? Inline base64 for thumbnails or just hide this feature in firefox?
Because the extension is awesome, and i haven't find anything even close to this. Can I help somehow to port?

**Comment by k-ivan** [comment]
Hello @notiv-nt  ). First of all, thanks for your attention to this issue. I myself still have a desire to create something similar for the Firefox, the solution seems to be there, but it takes time.

in more detail:

Firefox abandoned that specification, it was implemented only by Google Chrome.

base64 is not suitable due to the heavy load on the processor during parsing, with a large number of bookmarks in the folder, the page itself will slow down.

But instead of the file system, I can use a indexDB. This could actually be a working solution.

And there is another unpleasant moment related to chrome, from next year the version of the manifest will be changed, and the api. And there all the functionality of the background page will fall off, and I still do not see a way out to somehow alter it. And this topic is also worth studying in the documentation of the Firefox, how it works for them and whether they plan to change it in the near future.

**Comment by visbook** [comment]
Not a Chrome user but recently stumbled across Visual Bookmarks and have to say it is just excellent, and would be very eager to have a Firefox version to replace the also brilliant and feature rich but abandoned ViewMarks- https://github.com/wilgaboury/super-speedy-dial/issues/5

I think this is the same Michael Koch who coded ViewMarks- https://github.com/d3v-one
Maybe, if approached, he might be willing to offer some assistance/ code to speed up the port to Firefox.

Also, are you saying in your last sentence that Visual Bookmarks will not work after chrome change the api next year?

**Comment by k-ivan** [comment]
There are a few things to check now
- how optimal will it be to transfer the storage of images to the database, will the amount of memory consumed at the same time increase due to the many previews on the page
- but the most important thing is to prepare the current extension in chrome for it to work in the new version of the manifest. Based on what they did there, I do not see yet the possibility of saving a large number of functionality. That is, I will have to abandon some of the features that are now

Of course, I would like to keep the extension working and extend it for firefox, I will try to come up with something before chrome changes the manifest. But for now, what I see is that some of the functionality will have to be abandoned.

**Comment by regisnox** [comment]
Hello k-ivan

Is there any way You can port this to Firefox or/and for Opera?
Your extension is the best there is for speed dials and after recent changes in Chrome it would be awesome to use it on Firefox and Opera. 
Is there anything we can do as a comunity to help You with this project?

**Comment by k-ivan** [comment]
Hello @regisnox !

Glad you like it :)
Since the last discussion, I have not yet returned to this issue. But the main problem that was associated with the storage of images has already been resolved in favor of the IndexDB.
But unfortunately in Firefox there are still missing API(for example, favicon API). Other API items need to be checked as well.
By the way, the extension should work in Opera, I haven’t used it for a long time, but it definitely worked before when installed from the Chrome Store.

Closer to the new year, the main task will be to transfer the extension to manifest V3, after which it will be possible to return to this issue again, but without the missing api it is difficult.

**Comment by regisnox** [comment]
I was able to run it on my Opera now! But its not working in new tabs/speedial only as start page. So its probably some minor change but I was unable to find it how to stick it to new tab/speedial

**Comment by k-ivan** [comment]
Yeah, Opera doesn't support the newtab replacement option. Therefore the extension cannot be displayed as a default tab.

**Comment by k-ivan** [comment]
If suddenly someone else is waiting 😄
After recent major changes, migrating the image store to IndexDB, I think it's time to try porting the extension to Firefox.
There are a few other minor issues, but they seem to be fixable.

**Comment by da3dsoul1** [comment]
Looking forward to the firefox port if it's at all possible, this is an amazing extension, having it on firefox would be superb!

**Comment by k-ivan** [comment]
> Looking forward to the firefox port if it's at all possible, this is an amazing extension, having it on firefox would be superb!

Yes, it’s possible, all the preparatory work has been done, but so far I don’t have enough time to do the transfer.  But I plan to finish what I started 💯

**Comment by C-O-D** [comment]
Wow, that's really nice to hear!

**Comment by regisnox** [comment]
Any progress? After recent Chrome changes moving to Firefox have even more sense now. 
Can we support you somehow for your work?

**Comment by k-ivan** [comment]
Sorry, currently busy with my full-time job. I haven't forgotten about this problem.

**Comment by k-ivan** [comment]
- [ ] focus on search at startup
- [ ] show back column in bookmarks
- [ ] default bookmark folders
- [ ] range slider styles
- [ ] sort by type - folders
- [ ] requesting permission to access sites (does not work in Firefox by default)

**Comment by notiv-nt** [comment]
@k-ivan is it time to release ?

**Comment by k-ivan** [comment]
> @k-ivan is it time to release ?

Yes, i think i can try. i got distracted again, i will try to try it this weekend.

**Comment by notiv-nt** [comment]
Works as debugged addon from folder `extension`
![image](https://github.com/user-attachments/assets/513105b7-9cfd-468f-80c2-67e2fe6e8537)


but can't install as zip file
![image](https://github.com/user-attachments/assets/0c088c40-2676-4690-a94b-3772580597d3)

**Comment by k-ivan** [comment]
Hello everyone!

The [Firefox](https://addons.mozilla.org/en-US/firefox/addon/visual-bookmarks-firefox/) version is available for installation. There are limitations, unfortunately Firefox does not have some APIs. But I really hope that it will work and be useful to someone.

At this time I am closing this issue.
