### ISSUE TITLE
Windows 10 notifications

### ISSUE THREAD

**Issue by drtao69** [k-ivan/visual-bookmarks-chrome#4]
This extension keeps sending notifications to the Win110 Notifications area that are generally unhelpful.

This is one of them:
![visualbm](https://user-images.githubusercontent.com/34344448/44309061-34b4a800-a386-11e8-8e29-6b8f2f0de906.PNG)

There is another that says "offline".

This just started happening about 3-4 days ago and I am about ready to remove this extension.

**Comment by k-ivan** [comment]
@drtao69 thanks for the feedback. 

Since version 68, Chrome has begun to support the Windows 10 Action Notification Center.
I added the ability to test the network connection for the purposes of the experiment, in theory this notification should only pop up when a physical connection is lost. But this is not the most reliable way to check the availability of the Internet.
could you clarify, this notice appears to you without any reason for losing connection? In this case, I will remove this check.

**Comment by k-ivan** [comment]
@drtao69 since I did not receive a response from you, I will keep this check.
