### ISSUE TITLE
 Filter + Tags

### ISSUE THREAD

**Issue by yairbaricot** [k-ivan/visual-bookmarks-chrome#42]
First of all, this extension looks fantastic to me, thanks.

Can you add the function of tagging each bookmark so that you can filter a search to find one or more bookmarks that belong to the same category or group? 
For example: #Music #Indie #DigitalStore

**Comment by k-ivan** [comment]
Hi @yairbaricot!  Glad you like it.
This question has already been raised, I promise to think about it, but so far I have no idea how to implement this.

**Comment by k-ivan** [comment]
Sorry, but I will close this issue.

- It is not very convenient to store links between bookmarks and custom groups.
- Folders are basically the same as categories. And the bookmark search can search not only bookmarks but also folders with bookmarks.

You can organize your bookmarks into folders and use the search field to search for folder names.
There is one caveat, you will have to make one click more in order to enter the desired folder after the search, but this functionality is already there and working.
